### PR TITLE
Improve UX of first page readme

### PR DESCRIPTION
**Pull request by theosanderson**
Makes images that the user expects to be links behave as links to the right pages, rather than to the image in question.

Super minor suggestion, but I have found myself hitting this several times as a user. Feel free to reject!

### CODE REVIEW

**Comment by beniroquai** [comment]
Hey @theosanderson, thanks for this fix! I appreciate that! 
By the way, I got to know your name from the opentrons founder recently. Very cool work you do there! I hope to get one in our lab soon too! UC2 + opentrons, that would be something! :-)

**Comment by theosanderson** [comment]
Aw thanks! Kudos on all this awesomeness!

**Comment by b286** [comment]
Hey, thank you so much for this neat trick! 
I was always annoyed by this default property of github, making the images as links to themselves, but I've never made the effort to find a simple and lasting solution to this. I really appreciate your suggestion.

**Comment by theosanderson** [comment]
No prob! The "#" thing actually is still pretty annoying because it scrolls you up to the top. I just played around and found possibly the least annoying thing for standalone images that aren't intended to be links: turning them into an anchor that links to itself:

https://github.com/bionanoimaging/UC2-GIT/compare/master...theosanderson:patch-1

(just for info!)

**Pull request merged**
